packages:
  - apps/*
  - packages/*
  - tools/*

allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: true
  workerd: true

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^7.0.2
  vite: npm:@voidzero-dev/vite-plus-core@1.0.0
  vite-plus: 1.0.0
  void: ^0.24.0
overrides:
  vite@*: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
  allowedVersions:
    vite: "*"
