// Blog database schema (SQLite / D1 + Drizzle).
// Business tables map to apps/api/docs/db.md sections 1–6. The auth tables
// (user/session/account/verification) are generated by void's Better Auth (see
// auth.ts) instead of hand-written; they map to db.md section 0.
import { sql } from "void/db";
import { check, index, integer, primaryKey, sqliteTable, text, uniqueIndex } from "void/schema-d1";

// 时间字段统一为 Unix 秒级时间戳（integer({ mode: "timestamp" })）。

// 1. posts
export const posts = sqliteTable(
  "posts",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    title: text("title").notNull(),
    slug: text("slug").notNull().unique(),
    description: text("description"),
    content: text("content").notNull(),
    coverUrl: text("cover_url"),
    status: text("status", { enum: ["draft", "published"] })
      .notNull()
      .default("draft"),
    categoryId: integer("category_id").references(() => categories.id, {
      onDelete: "set null",
    }),
    // 指向 Better Auth 的 user.id（auth 表由 void 生成，跨 schema 不建外键）
    authorId: text("author_id").notNull(),
    publishedAt: integer("published_at", { mode: "timestamp" }),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
    updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
  },
  (t) => [
    check("posts_status_check", sql`${t.status} IN ('draft', 'published')`),
    check(
      "posts_published_at_check",
      sql`(${t.status} = 'draft') OR (${t.publishedAt} IS NOT NULL)`,
    ),
    index("posts_status_published_at_idx").on(t.status, sql`${t.publishedAt} desc`),
    index("posts_category_id_idx").on(t.categoryId),
  ],
);

// 2. categories
export const categories = sqliteTable("categories", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// 3. tags
export const tags = sqliteTable("tags", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  name: text("name").notNull().unique(),
  slug: text("slug").notNull().unique(),
  description: text("description"),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});

// 4. post_tags
export const postTags = sqliteTable(
  "post_tags",
  {
    postId: integer("post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    tagId: integer("tag_id")
      .notNull()
      .references(() => tags.id, { onDelete: "cascade" }),
  },
  (t) => [primaryKey({ columns: [t.postId, t.tagId] }), index("post_tags_tag_id_idx").on(t.tagId)],
);

// 5. post_links（双链）
export const postLinks = sqliteTable(
  "post_links",
  {
    id: integer("id").primaryKey({ autoIncrement: true }),
    sourcePostId: integer("source_post_id")
      .notNull()
      .references(() => posts.id, { onDelete: "cascade" }),
    targetPostId: integer("target_post_id").references(() => posts.id, {
      onDelete: "set null",
    }),
    targetText: text("target_text").notNull(),
    createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  },
  (t) => [
    uniqueIndex("post_links_source_target_text_idx").on(t.sourcePostId, t.targetText),
    check(
      "post_links_no_self_check",
      sql`(${t.targetPostId} IS NULL) OR (${t.sourcePostId} != ${t.targetPostId})`,
    ),
    index("post_links_target_post_id_idx").on(t.targetPostId),
  ],
);

// 6. settings
export const settings = sqliteTable("settings", {
  key: text("key").primaryKey(),
  value: text("value").notNull(),
  createdAt: integer("created_at", { mode: "timestamp" }).notNull(),
  updatedAt: integer("updated_at", { mode: "timestamp" }).notNull(),
});
