// Generated by void init.
import { defineConfig } from "void/config";

export default defineConfig({
  worker: {
    compatibility_date: "2026-02-24",
  },
  inference: {
    appType: "static",
  },
});
